site_name: Jesse的读书笔记
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_truly_sane_lists
  - mdx_math:
      enable_dollar_delimiter: True  #for use of inline $..$

nav:
    - 简介: 'index.md'
    - C/CPP: 'cpp.md'
    - 操作系统: 'operating_system.md'
    - 计算机网络: 'network.md'
    - 系统编程: 'system_program.md'
    - 网络编程: 'network_program.md'
    - 数据库:
      - 缓存: 'database/redis.md'
      - DB: 'database/mysql.md'
      - 大数据: 'database/hive.md'